<!DOCTYPE html>
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
    <title>Async/Await</title>
    <meta name="description" content="">
    <meta name="viewport" content="width=device-width">
</head>
<body>
<script type="text/javascript">
/***** 문제: .then/catch 로 구성된 함수를 async/await 로 변경하기 *****/

class HttpError extends Error {
    constructor(response) {
        super(`${response.status} for ${response.url}`);
        this.name = 'HttpError';
        this.response = response;
    }
}

// .then/catch -----------------------------------------------------------------
function loadJson(url) {
    return fetch(url).then(response => {
        if (response.status == 200) {
            return response.json();
        } else {
            throw new HttpError(response);
        }
    })
}

// Ask for a user name until github returns a valid user
function demoGithubUser() {
    let name = prompt("Enter a name?", "test");

    return loadJson(`https://api.github.com/users/${name}`).then(user => {
        alert(`Full name: ${user.name}.`);
        return user;
    }).catch(err => {
        if (err instanceof HttpError && err.response.status == 404) {
            alert("No such user, please reenter.");
            return demoGithubUser();
        } else {
            throw err;
        }
    });
}

//demoGithubUser();

// async/await -----------------------------------------------------------------
async function asyncLoadJson(url) {
    let response = await fetch(url);

    if (response.status == 200) {
        return response.json();
    } else {
        throw new HttpError(response);
    }
}

// Ask for a user name until github returns a valid user
async function asyncDemoGithubUser() {
    let user;

    while(true) {
        let name = prompt("Enter a name?", "test");

        try {
            user = await asyncLoadJson(`https://api.github.com/users/${name}`);
            break; // no error, exit loop
        } catch(err) {
            if (err instanceof HttpError && err.response.status == 404) {
                alert("No such user, please reenter.");
            } else {
                // unknown error, rethrow
                throw err;
            }
        }
    }

    alert(`Full name: ${user.name}.`);
    return user;
}

asyncDemoGithubUser();
</script>
</body>
</html>